### ISSUE TITLE
Run The Pipeline Locally

### ISSUE THREAD

**Issue by halimaach** [broadinstitute/gnomad-mitochondria#39]
Hello,

I have applied the first part of the pipeline locally using the WDL script with Mutect2. I would also use this part of the pipeline locally. Is this possible? If so, what does 'participant_id/data' stand for?

Thanks 
Halima

**Comment by klaricch** [comment]
The scripts in gnomad_mitochondria/pipeline were written to run on a cloud-based framework so some edits would be needed to run locally. The participant data is the tsv download of the "data" tab in Terra (which consists of both metadata uploaded by the user as well as the outputs from running the WDL). Participant_id is a unique identifier for the samples (essentially the sample name with prohibited characters in Terra replaced with underscores). The readme (https://github.com/broadinstitute/gnomad-mitochondria#mitochondria) has more information on what specific columns of the participant data are needed for each step.

**Comment by klaricch** [comment]
Can you clarify which file is being supplied for the artifact_prone_sites_path? This is the one we typically use: https://github.com/broadinstitute/gnomad-mitochondria/blob/main/gnomad_mitochondria/resources/artifact_prone_sites.bed

Some of the resource files are loaded in on GRCh37 (the actual sequence of the mitochondria reference is the same in both GRCh37 and GRCh38).

**Comment by halimaach** [comment]
It was a silly mistake, I used the wrong file with the chrM contig and that was indeed the issue.

I have  more questions regarding the MatrixTable which is a required input for the 'add_annotations.py' script.
First, I have actually run the WDL script locally which is available here https://github.com/gatk-workflows/gatk4-mitochondria-pipeline. I tried to fill the table with the output data obtained from this script.
However, I  have concerns regarding the wgs_median_coverage and the freemix_percentage.
1. When I apply CollectWgsMetrics to my WGS fully aligned hg38 bam sample to get the median coverage (which is supposed to be the autosome coverage), the median I obtained is 0. However when I try to get the median coverage using the SamTools (depth), I am getting a median ~ 7000. I am not sure whether I can use this value as input! 
2. The freemix_percentage is also required and if it can be calculated with VerifyBamID which vcf file should be used?

**Comment by klaricch** [comment]
It looks like that's an older version of the WDL. The most recent version of the WDL is located here: https://github.com/broadinstitute/gatk/blob/master/scripts/mitochondria_m2_wdl/MitochondriaPipeline.wdl

There might be an issue with the bam or parameters provided to CollectWgsMetrics (maybe the reference file or intervals?) that result in a coverage of 0. Other tools can be used to calculate coverage, but the intervals should be restricted to only the autosomes.

There are some VCFs here (gs://gcp-public-data--broad-references/hg38/v0/contamination-resources) or also in the VerifyBamID repo (https://github.com/Griffan/VerifyBamID/tree/master/resource).
